name: TFSIT
favicon: null
layout_spectrum: 0.20389968622475863
typography_spectrum: 0.23860944900661707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.044465843588113785
  lightness: 0.7535737184807658
  saturation: 0.8893672416452318
  rhythmicContrast: 0.34144122269935906
purpose: []
